name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      ROS_DISTRO: noetic
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.ROS_DISTRO }}-${{ matrix.ROS_REPO }}-
      - name: Build and test the packages
        uses: ros-industrial/industrial_ci@0.10.0
